import type { LucideIcon } from 'lucide-react';
import { MessageCircle, MessagesSquare, Flag, Megaphone, BookOpen, Timer, Flame, EyeOff, CheckCircle2, Library, Shield, Skull, CalendarCheck, Trophy, Hash, TrendingUp, Layers, Zap, Crown, Infinity, Moon, Scroll, Siren, Scissors, MessageSquare, Sparkles, LayoutList, Star, ThumbsUp, Compass, Palette, Globe, BookMarked, Bookmark, GalleryVertical, UserCheck, Users, Award, Droplets, Dna, Medal, Gem, Egg } from 'lucide-react';

export const BADGE_ICON_MAP: Record<string, LucideIcon> = {
  MessageCircle,
  MessagesSquare,
  Flag,
  Megaphone,
  BookOpen,
  Timer,
  Flame,
  EyeOff,
  CheckCircle2,
  Library,
  Shield,
  Skull,
  CalendarCheck,
  Trophy,
  Hash,
  TrendingUp,
  Layers,
  Zap,
  Crown,
  Infinity,
  Moon,
  Scroll,
  Siren,
  Scissors,
  MessageSquare,
  Sparkles,
  LayoutList,
  Star,
  ThumbsUp,
  Compass,
  Palette,
  Globe,
  BookMarked,
  Bookmark,
  GalleryVertical,
  UserCheck,
  Users,
  Award,
  Droplets,
  Dna,
  Medal,
  Gem,
  Egg,
};
