export const SWATCHES = [
    { label: 'Purple', value: '#9370DB' },
    { label: 'Violet', value: '#7C3AED' },
    { label: 'Fuchsia', value: '#D946EF' },
    { label: 'Rose', value: '#F43F5E' },
    { label: 'Red', value: '#E6392E' },
    { label: 'Orange', value: '#F97316' },
    { label: 'Amber', value: '#F59E0B' },
    { label: 'Yellow', value: '#EAB308' },
    { label: 'Lime', value: '#84CC16' },
    { label: 'Emerald', value: '#10B981' },
    { label: 'Green', value: '#22C55E' },
    { label: 'Teal', value: '#14B8A6' },
    { label: 'Cyan', value: '#06B6D4' },
    { label: 'Sky', value: '#0EA5E9' },
    { label: 'Blue', value: '#3B82F6' },
    { label: 'Indigo', value: '#6366F1' },
    { label: 'Pink', value: '#EC4899' },
    { label: 'Slate', value: '#64748B' },
] as const;